### ISSUE TITLE
ImportError: No module named web.routes

### ISSUE THREAD

**Issue by AdamSzendrei** [devicehive/devicehive-video-analysis#1]
Hi,
thanks for the tutorial!

When I start **python daemon.py** I get the following error:
Traceback (most recent call last):
  File "daemon.py", line 25, in <module>
    from web.routes import routes
ImportError: No module named web.routes

Do you have an idea what the problem is? Which package shall I install?

**Comment by igor-panteleev** [comment]
Hi,
It seems that i miss `__init__.py` file in `web` dir.
Can you create this file(should be empty) and run **daemon.py**?
It should help.

**Comment by AdamSzendrei** [comment]
thanks a lot! It works!
But I'm still not connected to the device:
$[ERROR] 2018-03-15 19:30:44,539: Devicehive is not connected

**Comment by igor-panteleev** [comment]
Thanks for your feedback. I will fix `__init__.py` issue and add some other minor fixes once i have some time.
About your second question: Once you have run *daemon.py* you need go to http://127.0.0.1:8000/ and configure devicehive connection. Settings will be saved to file and connection should be established.
