### ISSUE TITLE
'pip install -r requirements.txt' fails

### ISSUE THREAD

**Issue by sungwonida** [devicehive/devicehive-video-analysis#8]
https://github.com/devicehive/devicehive-video-analysis/blob/4d0b4cd7a9818539da2a18e1818f66075f8d09fc/requirements.txt#L4

It runs well in most part, but it fails at this part.
When I run the command below,
`$ pip install -e git://github.com/devicehive/devicehive-python-webconfig.git@a792db1babcedb5baa68ec6ba6ebcf0041f20469#egg=devicehive_webconfig`

I get

> Obtaining devicehive_webconfig from git+git://github.com/devicehive/devicehive-python-webconfig.git@a792db1babcedb5baa68ec6ba6ebcf0041f20469#egg=devicehive_webconfig
  Updating /home/david/.virtualenvs/tf-yolo-demo/src/devicehive-webconfig clone (to revision a792db1babcedb5baa68ec6ba6ebcf0041f20469)
fatal: Could not parse object 'a792db1babcedb5baa68ec6ba6ebcf0041f20469'.
Command "git reset --hard -q a792db1babcedb5baa68ec6ba6ebcf0041f20469" failed with error code 128 in /home/david/.virtualenvs/tf-yolo-demo/src/devicehive-webconfig

`$ git reset --hard -q a792db1babcedb5baa68ec6ba6ebcf0041f20469`
> fatal: Could not parse object 'a792db1babcedb5baa68ec6ba6ebcf0041f20469'.

**Comment by igor-panteleev** [comment]
Hi,
thank you for your feedback. I have updated `requirements.txt` and some related code, so this demo now uses released version of `devicehive-webconfig`

**Comment by kmrabhay** [comment]
I am still getting same problem...

`venv) abhay@abhay-HP-Laptop-15q-ds1xxx:~/trell/devicehive-audio-analysis$ pip install -r requirements.txt

Collecting numpy==1.13.3 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/57/a7/e3e6bd9d595125e1abbe162e323fd2d06f6f6683185294b79cd2cdb190d5/numpy-1.13.3-cp36-cp36m-manylinux1_x86_64.whl (17.0MB)
    100% |████████████████████████████████| 17.0MB 97kB/s 
Collecting scipy==0.19.1 (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/0e/46/da8d7166102d29695330f7c0b912955498542988542c0d2ae3ea0389c68d/scipy-0.19.1-cp36-cp36m-manylinux1_x86_64.whl (48.2MB)
    100% |████████████████████████████████| 48.2MB 36kB/s 
Collecting resampy==0.2.0 (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/1c/85/275f54cca4ae05a70488016af5a833b5361abb53dd5c5f4c0a7af8d50c4c/resampy-0.2.0.tar.gz (322kB)
    100% |████████████████████████████████| 327kB 1.1MB/s 
Collecting PyAudio==0.2.11 (from -r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/ab/42/b4f04721c5c5bfc196ce156b3c768998ef8c0ae3654ed29ea5020c749a6b/PyAudio-0.2.11.tar.gz
Collecting tensorflow==1.3.0 (from -r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/7c/9f/57e1404fc9345759e4a732c4ab48ab4dd78fd1e60ee1270442b8850fa75f/tensorflow-1.3.0-cp36-cp36m-manylinux1_x86_64.whl (43.5MB)
    100% |████████████████████████████████| 43.6MB 41kB/s 
Collecting six==1.11.0 (from -r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting devicehive==2.1.1 (from -r requirements.txt (line 7))
  Downloading https://files.pythonhosted.org/packages/72/6f/93206fd6c0baf8ba2f8bffd3e2de69b59278387bd7252a99cc89914d0dcc/devicehive-2.1.1.tar.gz
Obtaining devicehive_webconfig from git+git://github.com/devicehive/devicehive-python-webconfig.git@a792db1babcedb5baa68ec6ba6ebcf0041f20469#egg=devicehive_webconfig (from -r requirements.txt (line 8))
  Cloning git://github.com/devicehive/devicehive-python-webconfig.git (to a792db1babcedb5baa68ec6ba6ebcf0041f20469) to /home/abhay/venv/src/devicehive-webconfig
  Could not find a tag or branch 'a792db1babcedb5baa68ec6ba6ebcf0041f20469', assuming commit.
fatal: reference is not a tree: a792db1babcedb5baa68ec6ba6ebcf0041f20469
Command "git checkout -q a792db1babcedb5baa68ec6ba6ebcf0041f20469" failed with error code 128 in /home/abhay/venv/src/devicehive-webconfi`

How do I fix this? Thanks/
