### ISSUE TITLE
It doesn't seem to open any of the YouTube videos

### ISSUE THREAD

**Issue by sungwonida** [devicehive/devicehive-video-analysis#9]
Of course, there are still many videos I haven't tried yet, but I couldn't get any successful result so far.
I ran 
`pip install -r requirements.txt`
with modified requirements.txt (due to this [issue](https://github.com/devicehive/devicehive-video-analysis/issues/8))
> -e git://github.com/devicehive/devicehive-python-webconfig.git#egg=devicehive_webconfig

then,
`python eval.py --video="https://youtube_url"`
> Traceback (most recent call last):
  File "eval.py", line 129, in <module>
    tf.app.run(main=evaluate)
  File "~/.virtualenvs/tf-yolo-demo/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "eval.py", line 47, in evaluate
    raise IOError('Can\'t open "{}"'.format(FLAGS.video))
OSError: Can't open "https://youtube_url"

**Comment by igor-panteleev** [comment]
Hi again,
I took a look to this problem.
It seem like something have been changed and i can't figure out what exactly. (best comment that i have found so far on [stackoverflow](https://stackoverflow.com/questions/37555195/is-it-possible-to-stream-video-from-https-e-g-youtube-into-python-with-ope?answertab=votes#comment84535864_47439552))

Best solution that i have for now is to download video in advance and than use it like
```bash
python eval.py --video=/path/to/your/video/file.mp4
```
I will try to figure out how to fix this.

**Comment by sungwonida** [comment]
@igor-panteleev Thanks for responding. I tried what you suggested, it works great. YOLO(I guess that is version 2) is pretty slow on my device, so it seems better to download the video and then run the demo, otherwise, I'm guessing it's gonna be much slower due to the transaction.
